#!/usr/bin/env bash

rm -rf pastore-cli pastore-cli.tar.gz
mkdir pastore-cli
gulp prod
cp -r build bin package.json install pastore-cli
chmod 700 pastore-cli/install
tar -zcf pastore-cli.tar.gz pastore-cli/*
rm -rf pastore-cli
