#!/usr/bin/env bash

current=$PWD

rm -rf $HOME/.pastore-cli
mkdir $HOME/.pastore-cli
cp -r ./* $HOME/.pastore-cli
cd $HOME/.pastore-cli
npm i --production

cd $current

echo "You will need to set up the PATH environment variable in your terminal to have access to pastore-cli's binaries globally."
echo "Add below line to your profile (this may be in your .profile, .bashrc, .zshrc, etc.)"
echo "export PATH=\"\$PATH:\$HOME/.pastore-cli/bin\""
